/* link.c — link dispatch and the null link. */
#include <string.h>
#include "link.h"
#include "gen.h"

static link_kind_t s_kind = LINK_NONE;
static int s_open;
static link_stats_t s_none;

void link_cfg_defaults(link_cfg_t *c)
{
    memset(c, 0, sizeof *c);
    c->kind = LINK_NONE;
    c->qspi_hz = 10000000U;          /* bring-up clock; raise only after the link test passes */
    c->qspi_rd_hz = 5000000U;
    c->qspi_dummy = HDEMG_QSPI_DUMMY_CYCLES;
    c->qspi_addr_lines = 4U;
    c->qspi_sshift = 1U;
    c->qspi_even = 1U;
    c->qspi_nocredit = 0U;
    c->sdio_hz = 25000000U;
    c->batch_max = HDEMG_LINK_MAX_FRAMES;
}

const char *link_name(link_kind_t k)
{
    switch (k) {
    case LINK_QSPI: return "qspi";
    case LINK_SDIO: return "sdio";
    default:        return "none";
    }
}

int link_open(const link_cfg_t *c, const char **err)
{
    int rc = 0;
    *err = "";
    if (s_open) link_close();
    switch (c->kind) {
    case LINK_QSPI: rc = link_qspi_open(c, err); break;
    case LINK_SDIO: rc = link_sdio_open(c, err); break;
    default:        memset(&s_none, 0, sizeof s_none); break;
    }
    if (rc == 0) { s_kind = c->kind; s_open = 1; }
    return rc;
}

void link_poll(int flush)
{
    if (!s_open) return;
    switch (s_kind) {
    case LINK_QSPI: link_qspi_poll(flush); break;
    case LINK_SDIO: link_sdio_poll(flush); break;
    default: {
        /* Null link: take everything at once. This is the generate-and-drop mode used to
         * check pacing with nothing attached; "accepted" bytes equal generated bytes. */
        const uint8_t *p;
        uint32_t n;
        while ((n = gen_peek(&p, GEN_RING_FRAMES)) != 0U) {
            gen_consume(n);
            s_none.bytes += (uint64_t)n * GEN_FRAME_BYTES;
            s_none.xfers++;
        }
        break;
    }
    }
}

void link_close(void)
{
    if (!s_open) return;
    switch (s_kind) {
    case LINK_QSPI: link_qspi_close(); break;
    case LINK_SDIO: link_sdio_close(); break;
    default: break;
    }
    s_open = 0;
}

void link_stats(link_stats_t *out)
{
    switch (s_kind) {
    case LINK_QSPI: link_qspi_stats(out); break;
    case LINK_SDIO: link_sdio_stats(out); break;
    default:        *out = s_none; break;
    }
}
